onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/clk
add wave -noupdate /tb_top/rst
add wave -noupdate /tb_top/dut/clk
add wave -noupdate /tb_top/dut/rst
add wave -noupdate /tb_top/dut/pc
add wave -noupdate /tb_top/dut/instruction
add wave -noupdate /tb_top/dut/fetch_valid
add wave -noupdate /tb_top/dut/decode_valid
add wave -noupdate /tb_top/dut/execute_valid
add wave -noupdate /tb_top/dut/commit_valid
add wave -noupdate /tb_top/dut/if_id_instr
add wave -noupdate /tb_top/dut/id_ex_instr
add wave -noupdate /tb_top/dut/ex_mem_instr
add wave -noupdate /tb_top/dut/mem_wb_instr
add wave -noupdate /tb_top/dut/opcode
add wave -noupdate /tb_top/dut/rd
add wave -noupdate /tb_top/dut/funct3
add wave -noupdate /tb_top/dut/rs1
add wave -noupdate /tb_top/dut/rs2
add wave -noupdate /tb_top/dut/funct7
add wave -noupdate /tb_top/dut/alu_result
add wave -noupdate /tb_top/dut/i
add wave -noupdate /tb_top/dut/u_fetch/clk
add wave -noupdate /tb_top/dut/u_fetch/rst
add wave -noupdate /tb_top/dut/u_fetch/stall
add wave -noupdate /tb_top/dut/u_fetch/flush
add wave -noupdate /tb_top/dut/u_fetch/branch_taken
add wave -noupdate /tb_top/dut/u_fetch/branch_target
add wave -noupdate /tb_top/dut/u_fetch/fetch_pc
add wave -noupdate /tb_top/dut/u_fetch/instruction
add wave -noupdate /tb_top/dut/u_fetch/current_pc
add wave -noupdate /tb_top/dut/u_fetch/next_pc
add wave -noupdate /tb_top/dut/u_fetch/pc_inst/clk
add wave -noupdate /tb_top/dut/u_fetch/pc_inst/rst
add wave -noupdate /tb_top/dut/u_fetch/pc_inst/stall
add wave -noupdate /tb_top/dut/u_fetch/pc_inst/flush
add wave -noupdate /tb_top/dut/u_fetch/pc_inst/next_pc
add wave -noupdate /tb_top/dut/u_fetch/pc_inst/pc
add wave -noupdate /tb_top/dut/u_fetch/npc_inst/current_pc
add wave -noupdate /tb_top/dut/u_fetch/npc_inst/branch_taken
add wave -noupdate /tb_top/dut/u_fetch/npc_inst/branch_target
add wave -noupdate /tb_top/dut/u_fetch/npc_inst/next_pc
add wave -noupdate /tb_top/dut/u_decode/instruction
add wave -noupdate /tb_top/dut/u_decode/opcode
add wave -noupdate /tb_top/dut/u_decode/rd
add wave -noupdate /tb_top/dut/u_decode/funct3
add wave -noupdate /tb_top/dut/u_decode/rs1
add wave -noupdate /tb_top/dut/u_decode/rs2
add wave -noupdate /tb_top/dut/u_decode/funct7
add wave -noupdate /tb_top/dut/u_rs/clk
add wave -noupdate /tb_top/dut/u_rs/rst
add wave -noupdate /tb_top/dut/u_rs/dispatch_en
add wave -noupdate /tb_top/dut/u_rs/src1_tag
add wave -noupdate /tb_top/dut/u_rs/src2_tag
add wave -noupdate /tb_top/dut/u_rs/dest_tag
add wave -noupdate /tb_top/dut/u_rs/src1_ready
add wave -noupdate /tb_top/dut/u_rs/src2_ready
add wave -noupdate /tb_top/dut/u_rs/instruction
add wave -noupdate /tb_top/dut/u_rs/issue_grant
add wave -noupdate /tb_top/dut/u_rs/issue_index
add wave -noupdate /tb_top/dut/u_rs/rs_full
add wave -noupdate /tb_top/dut/u_rs/free_index
add wave -noupdate /tb_top/dut/u_rs/found_free
add wave -noupdate /tb_top/dut/u_rs/#ublk#181339534#77/i
add wave -noupdate /tb_top/dut/u_rs/#ublk#181339534#112/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 343
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {443022 ps}
